# Generated by Django 3.0.9 on 2020-09-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type',
            new_name='account_type',
        ),
        migrations.AddField(
            model_name='account',
            name='current_class',
            field=models.CharField(choices=[('1', 'Standard 1'), ('2', 'Standard 2'), ('3', 'Standard 3'), ('4', 'Standard 4'), ('5', 'Standard 5'), ('6', 'Standard 6'), ('7', 'Standard 7'), ('8', 'Form 1'), ('9', 'Form 2'), ('10', 'Form 3'), ('11', 'Form 4'), ('12', 'Form 5')], default=1, max_length=50, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='school_attending',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
