# Generated by Django 3.0.9 on 2020-08-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.account',),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.account',),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TUTOR', 'Tutor')], default='STUDENT', max_length=50, verbose_name='Type'),
        ),
    ]
