# Generated by Django 3.0.9 on 2020-08-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200810_2157'),
        ('student_portals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologyassignmentgrades',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student'),
        ),
        migrations.AlterField(
            model_name='chemistryassignmentgrades',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student'),
        ),
        migrations.AlterField(
            model_name='mathematicsassignmentgrades',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student'),
        ),
        migrations.AlterField(
            model_name='physicsassignmentgrades',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student'),
        ),
    ]
